version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ../.env
    networks:
      - db_network

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:27017
    networks:
      - db_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DATABASE_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@mongo:${DATABASE_PORT}/
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  mongodb-data: